---
title: '这几年'
date: '2022-07-04'
categories: ['life']
description: '离开深圳前一些想说的话'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---


> *"有个阴天，没有下雨，但我到公司后还是和前台借了一把伞，过了几天准备下楼还伞的时候，外面却下起了大雨，而那天很多人都没伞。"*

## 流水账

2020年初拿到港中文offer，从上一家公司离职后，一直踌躇满志，找了很多关于如何学习计算机的资料，想着自己终于可以做自己喜欢的事情了。于是在闵行租了一个小屋子， 天天闷在里面学习、打游戏、抽烟、睡懒觉，日复一日。

过了几个月，去了西安和女朋友呆一起，本来以为过不了多久就去香港了，结果疫情严重，全部改为网课，就这样一边上网课，一边试了下秋招，结果一律过不了初面。终于发现，学校教的和工作需要的其实并不完全一致。但不管怎样，虽说是上网课，也和几个同学相谈甚欢，学到了不少。

就这样，直到十二月份，我才开始看一些培训班的视频，开着两倍速，不知道比刚开始抱着《JAVA核心技术》一个字一个字啃要快多少倍。很快，十二月底，拿到了腾讯的实习和华为的留学生秋招offer。

在腾讯实习了几个月之后又去了阿里实习，后来秋招又拿了一些offer，最后在2021年底正式入职腾讯。

再后来，从今年4月初开始，日子一直不好过，为了避免被裁或是为了缓解老板的焦虑，我们表演式加班，一天又一天。结果6月27号还是通知我被裁了，可笑的是，第二天又被通知有应届生保护政策留下了（事实上我早就想走了），最后经过一番协商，也给了些赔偿。现在发这篇博客的时候离我离职日期正好还剩一周。

## 慎

我平时爱玩英雄联盟，也感谢腾讯每个月业务体验福利让我这个穷b摇身一变成了皮肤狗。但我现在爱玩这个游戏和刚开始玩它的理由已经有了很大不同。刚开始是因为大家都玩，军校里也没啥别的娱乐方式，去游戏里杀人排解烦闷罢了。现在我倒是会研究各个英雄的台词。虽说也是人编出来的，但多少给我点启发。

就比如暮光之眼-慎，他有几句台词：

> *"Tread carefully（要步步为营）"*

> *"A demonstration of superior judgement（您果然深思熟虑）"*

从去年实习开始，我就骑驴找马，再后来拒秋招offer的时候，我给的理由都是我去读博了，事实上我确实有考虑读博。然后今年四月份的某个加班到十点的晚上，我在回家的路上突然就决定去要回我去年的offer。

无奈过程令人煎熬，一直到通知被裁后两周才最终敲定，这三个月滋味真不好受。但有时候想想我那装精神病三个月，期间一次没碰过电子产品的军校同学，大概也有异曲同工之妙吧。

现在回想起来，慎这个英雄大概真的影响到了我，要时刻保持谨慎，要有全局思维。而我做这些决定的时候，并没有想太多，大概就类似于游戏里的**肌肉记忆**吧。

## Ambition

为什么会突然想到Ambition这个选手呢？因为我2017年退伍，病床上看S7的比赛，看EDG一万经济被翻盘，看EDG的粉丝在赛场外哭到呕吐。而那一年Ambition打败Faker，拿下了S7的冠军，我却考研失败。

但回顾Ambition的职业生涯，2012年以中单成名，2013年被Faker单杀，开始走下坡路，那一年正好我进入科大。

所以我觉得我的2017年过的并不失败，大概我心中住了一个Ambition吧。

## 朋友

我有几个同学，平时喜欢一起玩英雄联盟，喜欢四黑然后在快赢的时候点投降，喜欢一起住电竞酒店，喜欢抽着烟漫步在凌晨的淮海中路被人问要不要代驾（其实是需要代练），喜欢在KTV听渣威的《童话镇》、阿杰的《像我这样的人》、阿煊的《夏日寒风》却没钱点酒，喜欢找女陪玩结果发现大部分除了发嗲别的啥都不会。

就这样过了几年，直到大家都没力气通宵，没力气抽烟，直到唯一一个打的很好的女陪玩也弃游了，直到大家都有了女朋友甚至老婆。

我们最近一次共同经历的事已经不是英雄联盟了，居然是部队问我们要那多发的两个月津贴，大伙都不想给，于是支付了一杯奶茶钱当律师费，然后心满意足地发现自己当老赖的想法得到了律师的认可。

但我还是会每天上游戏玩个一两把，看着右边黑乎乎的好友栏，看着只有一个亮起的ID，那个人叫“还在等她说晚安”。

## 工作

算上实习，算上陆院那几个月，也工作了快四年了，期间兜兜转转，从南昌到上海，从上海到深圳，现在又回到上海，我一直嘲笑老婆工作不稳定，老是出差，但她都在同一个地方工作五年了，我却换了五个地方。

## 未来

最近在重读古龙，后面计划写些读后感，希望能赚点钱买纸质书而不是网上下盗版，希望家里房子顺利盖好，希望家人和朋友身体健康、工作顺利。

