project:
  type: website
  
format:
  html:
    theme: 
      light: theme.scss

website:
  title: "Love Camille" 
  site-url: https://lov3camille.top
  description: "This is Lov3Camille's personal Blog."
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - icon: github
        href: https://github.com/Lov3Camille
      - icon: twitter
        href: https://twitter.com/lov3camille_
#########################
# You can ignore this part in the first step
      - icon: rss
        href: blog.xml
      - text: Resources
        menu: 
          - text: OSCHINA
            href: https://www.oschina.net/
      - text: Archive
        href: archive.qmd
  google-analytics: G-HYPHER2H36
  cookie-consent: true
  twitter-card: 
    image: thumbnail_blog.png
    card-style: summary_large_image
    creator: "@lov3camille"

filters:
  - code-filename
  - lightbox

lightbox: auto
#########################  
  
editor: source

