---
title: '<克拉拉与太阳>读后感'
date: '2022-12-18'
categories: ['reading']
description: ' '
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

## 写在之前的话

很久没写过读后感了，上次写应该还是在高中，从小学到高中读过很多书和期刊，也正是这些书塑造了我的一部分人格，所以我必须感谢这些书，以及给予我阅读条件的爸妈、外婆、老师。

关于《克拉拉与太阳》这本书，从买回来到读完，花了快一年，深圳买来，上海读完，期间也换了工作，经历了似乎发生了很多事又似乎什么都没发生的2022年。

至于我为什么花了一年才读完，相信现代人很能理解，因为手机和电脑已经占据了我们的工作与生活，重新拿起纸质书本就不容易。但仔细一想，其实每天读一些也能很快读完，说到底还是自己懒，但毕竟这是这几年第一本完整读完的纸质书，值得纪念一下。

## 什么是克拉拉

克拉拉是一个专为陪伴儿童而设计的太阳能人工智能机器人，具有极高的观察、推理与共情能力。 

## 什么是太阳

回到这本书上，我是在一个沐浴着午后的阳光的图书馆里读完的这本书，同时身边可能还充斥着很多新冠阳性病人，那么这本书里的太阳是什么呢？

天真的克拉拉（人工智能机器人）相信太阳有神奇的力量，可以治愈疾病，而实际上乔西也确实在沐浴阳光后渐渐好转，这奠定了这是一本童话的基础，因为众所周知太阳并不能治愈疾病。然而对于克拉拉来说，
太阳可以为其提供能量，所以对她来说太阳就是她心中的上帝，类似于人类社会中基督教的上帝，或者佛教的如来等。所以当我们去寺庙或者在胸口画十字架的时候，我们是否也很天真呢？

当然，除了物理意义上的太阳，还有一个很重要的点，那就是*爱*， 不管是克拉拉之于乔西，抑或里克之于乔西，克里西之于乔西，都是*爱*，一种如暖阳般温暖我们却又看不见摸不着的东西。

正是因为这些爱，才有了最后完美的结局。这让我想起了诺兰的《星际穿越》，一部完美地诠释了什么叫做“*爱*可以穿越时空”的电影。

## 关于结局

我是一个喜欢好的结局但又不希望好的作品就此陷入窠臼的人，这不是出于自认为能看透一切的自负或是受“喜剧的内核是悲剧”之类言论的影响。因为我始终认为好的作品，书或者电影，是需要留给读者和观众一定的想象空间的，类似于“留白”
